### ISSUE TITLE
Add obstacles to duck under

### ISSUE THREAD

**Issue by paulshriner** [pwsdc/playdate-runner#7]
The ducking mechanic is present but all obstacles are on the ground, there should be some in the air that the player can duck under. Since all ground obstacles are at the same y level I think the simplest way to do this would be to find the y offset to raise the block so the player can duck under, then randomly apply it to the obstacles.

Also the player's collision box is not correct when ducked, it allows for phasing right through obstacles (you should hit into obstacles even when ducked). This is related enough that it can be fixed at the same time as adding obstacles to duck under.

**Comment by lavender-aa** [comment]
player is no longer invincible when ducking
